FROM node:20-slim

ARG UID=1000
ARG GID=1000

# Create a group and user to run the application
RUN groupadd -o -g ${GID} app && \
    useradd -m -o -u ${UID} -g app app

WORKDIR /app

# Fix ownership
RUN chown -R app:app /app

# Switch user BEFORE npm install
USER app

# Copy entrypoint
COPY --chown=app:app scripts/entrypoint.sh /app/scripts/entrypoint.sh
RUN chmod +x /app/scripts/entrypoint.sh

EXPOSE 5173

ENTRYPOINT ["/app/scripts/entrypoint.sh"]
