services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        UID: ${UID:-}
        GID: ${GID:-}
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/app:z
